### ISSUE TITLE
Удаление диалогов

### ISSUE THREAD

**Issue by podolsky4** [podolsky4/TextMessenger#122]
При **удалении диалогов дожны удаляться все связанные с ним сообщения пользователей**, иначе они будут хранится в базе данных как мусор

**Comment by podolsky4** [comment]
А что делать с сообщениями (MESSAGES) которые связанны с конкретным диалогом?

**Comment by Fandorinxxx** [comment]
Для СБУ оставлять)))

**Comment by 4val0v** [comment]
Ну как сказал @korsa719 удалять сам диалог когда в нем уже не останется пользователей
В ВК можно создать беседу, выйти даже всем пользователям, она не удаляется, но есть возможность вернуться в беседу обратно, можно так-же реализовать

И если не секрет, что за курс проходите ?? __(Хочу к вам если можно онлайн)__
