### ISSUE TITLE
Post DTO

### ISSUE THREAD

**Issue by podolsky4** [podolsky4/TextMessenger#125]
Компоненты Post должен получать только необходимую информацию для отрисовки, которая пришла с сервера, тоесть к примеру PostResponseDto - это DTO который пришел с сервера, приблизительный вид:
```
{
  "postId": 1,
  "userId": 3,
  "firstName": "Sarah",
  "lastName": "Garcia",
  "profilePhoto": "https://www.userme.....",
  "createdDate": "12-02-2011T12:57+03Z"
  "content": "Some text of post...",
  "favorite": true,
  "likesCount": 12,
  "repostPost": true,
  "repostsCount": 34,
  "commentsCount": 6,
  "latestComments": [...]
}
```

**Comment by podolsky4** [comment]
Из-за перегруженности Реакт компонентов, приходиться делать множество запросов на сервер чтобы получить всю необходимую информацию для отображения

**Comment by korsa719** [comment]
тут если на примере ты юзера лайки пост и прочее запихнул в одно

**Comment by podolsky4** [comment]
Это и есть необходимая информация чтобы отрендерить пост, уж лучше сразу все получить чем ждать пока придут все запросы

**Comment by podolsky4** [comment]
При создании  нового поста должен только возвращатся этот только что созданый пост и HTTP STATUS 201 CREATED, заново загружать посты не нужно
